controllers/RecordsController.php
<?php

namespace app\controllers;

use app\models\records\Cdr;
use app\models\CdrProfile;
use app\models\records\CdrSearch;
use app\models\records\RecordInfo;
use app\models\sipconfig\SipGroup;
use app\models\User;
use Yii;
use yii\base\ExitException;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use dektrium\user\Finder;
use yii\base\Module as Module2;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

class RecordsController extends Controller
{
    /** @var Finder */
    protected $finder;

    /**
     * @param string  $id
     * @param Module2 $module
     * @param Finder  $finder
     * @param array   $config
     */
    public function __construct($id, $module, Finder $finder, $config = [])
    {
        $this->finder = $finder;
        parent::__construct($id, $module, $config);
    }
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    private function getNavBar(CdrProfile $cdrProfile)
    {
        $menuItems[] =
            [
                'label'   => Yii::t('app', 'My Calls'),
                'url'     => ['/records/my-records'],
                'active' => strstr(Yii::$app->request->getUrl(), '/records/my-records'),
            ];
        if(Yii::$app->user->can('listenGroupCalls')) {
            $groups = ArrayHelper::map($cdrProfile->userGroups, 'id', 'group_name');
            foreach ($groups as $groupId => $groupName) {
                $menuItems[] = [
                    'label' => Yii::t('app', $groupName),
                    'url'     => ['/records/group?id=' . $groupId],
                    'active' => strstr(Yii::$app->request->getUrl(), '/records/group?id=' . $groupId),
                ];
            }
        }

        return $menuItems;
    }
    /**
     * Lists all Cdr models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->redirect('records/my-records');
    }

    public function actionMyRecords()
    {
        $cdrProfile = $this->findModel(Yii::$app->user->id)->cdrProfile;
        /**
         * Set default values for current user
         * @link http://www.yiiframework.com/wiki/663/yii2-default-values-for-index-data-provider/
         */
        $searchModel = new CdrSearch([
            'calldate' => date('Y-m-d', time()),
            'channel' => $cdrProfile->sip_account,
            'dstchannel' => $cdrProfile->sip_account,
            'dcontext' => $cdrProfile->allContexts,

        ]);
        $searchModel->scenario = CdrSearch::SCENARIO_SEARCH_MULTIPLE_RECORDS;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('cdr_test', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'navBar' => $this->getNavBar($cdrProfile),
            'channel' => [],
        ]);
    }

    public function actionGroup($id)
    {
        if (Yii::$app->user->can('listenGroupCalls')) {
            $group = new SipGroup(['id' => $id]);
            $users = $group->users;
            $channel = [];
            $dcontext = [];
            foreach ($users as $user) {
                /**
                 * при формировании списка пользователей состоящих в группе
                 * исключаем из этого списка тех кто может слушать вызовы
                 * своей группы. Т.к. туда попадал как сам владелец аттрибута 'listenGroupCalls'
                 * так и владельцы из других отделов (групп).
                 */
                $userRoles = Yii::$app->authManager->getRolesByUser($user->id);
                if (!array_key_exists('listenGroupCalls', $userRoles))
                {
                    $channel[$user->cdrProfile->inner_phone] = $user->cdrProfile->sip_account;
                    $dcontext = array_unique(array_merge($dcontext, $user->cdrProfile->allContexts));
                }
            }
            $searchModel = new CdrSearch([
                'calldate' => date('Y-m-d', time()),
                'channel' => $channel,
                'dstchannel' => $channel,
                'dcontext' => $dcontext,

            ]);
            $searchModel->scenario = CdrSearch::SCENARIO_SEARCH_MULTIPLE_RECORDS;
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $cdrProfile = $this->findModel(Yii::$app->user->id)->cdrProfile;
            return $this->render('cdr_test', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'navBar' => $this->getNavBar($cdrProfile),
                'channel' => array_flip($channel),
            ]);
        }
        throw new ForbiddenHttpException("Sorry, you don't have access to this action.");
    }

    public function actionDetails()
    {
        Url::remember('', 'actions-redirect');
        $model = new CdrSearch();
//        $model->scenario = CdrSearch::SCENARIO_SEARCH_RECORD_BY_ID;
        $dataProvider = $model->searchById(Yii::$app->request->get());
        $infoModel = $model->getRecordInfo();
        if ($infoModel === null) {
            $infoModel = Yii::createObject(RecordInfo::className());
            $infoModel->link('record', $dataProvider);
        }

        return $this->renderPartial('detailview/_cdr_detail',[
            'model' => $dataProvider,
            'infoModel' => $infoModel,
        ]);
    }

    public function actionDetailsUpdate($id)
    {
        $model = new CdrSearch(['acctid' => $id]);
        $infoModel = $model->getRecordInfo();
        Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'id' => $id,
            'isUpdated' => $infoModel->load(Yii::$app->request->post()) && $infoModel->save(),
        ];
    }

    public function actionClientSearch()
    {
        if (Yii::$app->request->get('channel') === null) {
            throw new BadRequestHttpException("Required params is not found");
        }
        if (Yii::$app->request->get('phone') === null) {
            throw new BadRequestHttpException("Required params is not found");
        }
        $model = new CdrSearch();
        $model->scenario = CdrSearch::SCENARIO_SEARCH_SRC_OR_DST_BY_PHONE;
        Yii::$app->response->format = Response::FORMAT_JSON;
        $result = $model->searchByPhone(Yii::$app->request->get());
//        $channel = Yii::$app->request->get('channel') ? Yii::$app->request->get('channel') : $this->findModel(Yii::$app->user->id)->cdrProfile->sip_account;
        //$query = CdrSearch::find()->select(['building_name'])->where(['like', 'building_name', $term])->limit('10')->column();
        //print_r($term); exit;
        //return $query;
        return $result;
    }


    public function actionDebug($date = null)
    {
        if (is_null($date) or !$this->validateDate($date, 'Y-m-d')) {
            $date = date('Y-m-d', time());
        }
//        $profile = User::findOne(Yii::$app->user->identity->id)->profile;
//        $cdrProfile = User::findOne(Yii::$app->user->identity->id)->cdrProfile;
//        var_dump($cdrProfile->sip_account);
//         die;

        $currentUser = Yii::$app->user;
        if ($currentUser->can('salesManager') && $currentUser->can('viewRecords')) {
            $sips = ArrayHelper::map(CdrProfile::find()->asArray()->all(), 'user_id', 'sip_account');
            $model = Cdr::getCallDetailRecordsForUser($sips, $date);
            $datesModel = Cdr::getDatesOfCalls($sips, $date);
            return $this->render('cdr',[
                'model' => $model,
                'datesModel' => $datesModel,
                'currentUrl' => true,

            ]);
        } elseif ($currentUser->can('salesManager')) {
            $cdrProfile = User::findOne(Yii::$app->user->identity->id)->cdrProfile;
            $model = Cdr::getCallDetailRecordsForUser($cdrProfile->sip_account, $date);
            $datesModel = Cdr::getDatesOfCalls($cdrProfile->sip_account, $date);
            return $this->render('cdr', [
                'model' => $model,
                'datesModel' => $datesModel,
            ]);
        }
        throw new ForbiddenHttpException("Forbidden access");
    }

    public function actionOperator($number = null, $date = null) {
        if (is_null($date) or !$this->validateDate($date, 'Y-m-d'))
            $date = date('Y-m-d', time());

        if (!isset($number))
            throw new BadRequestHttpException("Operator must be specified");

        $userRoleArray = Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId());
        $targetUserRoleArray = Yii::$app->authManager->getRolesByUser(CdrProfile::getUserIdByInnerPhone($number));
        if (count($userRoleArray) > 1 or count($targetUserRoleArray) > 1)
            throw new BadRequestHttpException("Current user have more than 1 role. This is bad!");

        $currentUserRoleObject = array_pop($userRoleArray);
        $targetUserRoleObject = array_pop($targetUserRoleArray);

        if ($currentUserRoleObject == $targetUserRoleObject and Yii::$app->user->can('viewRecords')) {
            $targetUserCdrProfile = User::findOne(CdrProfile::getUserIdByInnerPhone($number))->cdrProfile;
            $model = Cdr::getCallDetailRecordsForUser($targetUserCdrProfile->sip_account, $date);
            $datesModel = Cdr::getDatesOfCalls([$targetUserCdrProfile->sip_account], $date);
            return $this->render('cdr', [

views/records/_cdr_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'creation_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
        <?= Html::submitButton('Сбросить', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/records/_cdr_search_operator.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\records\CdrOperatorSearch */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="post-search">
    <?php $form = ActiveForm::begin([
//        'action' => [''],
        'method' => 'get',
        'options' => [
        ],
    ]); ?>

    <?= $form->field($model, 'channel')->widget(\kartik\select2\Select2::classname(), [
        'data' => ['SIP/403' => '403', 'SIP/404' => '404', 'SIP/405' => '405'],
        'theme' => 'bootstrap',
        'maintainOrder' => true,
        'size' => 'sm',
        'options' => [
            'placeholder' => 'Select operator ...',
            'multiple' => true,
        ],
        'pluginOptions' => [
            'allowClear' => true,
            'data' => true,
        ],
        'addon' => [
            'prepend' => [
                'content' => Html::tag('span','',['class' => 'glyphicon glyphicon-earphone'])
            ],
            'append' => [
                'content' => Html::submitButton(Html::tag('span', '', ['class' => 'glyphicon glyphicon-search']),
                    [
                    'class' => 'btn btn-primary',
                    'title' => 'Search',
                    'data-toggle' => 'tooltip',
                    'data-placement' => 'right',
                    ]),
                'asButton' => true,
            ],
        ],
//        'pluginEvents' => [
//            "change" => "function() { log('change'); }",
//            "select2:opening" => "function() { log('select2:opening'); }",
//            "select2:open" => "function() { log('open'); }",
//            "select2:closing" => "function() { log('close'); }",
//            "select2:close" => "function() { log('close'); }",
//            "select2:selecting" => "function() { log('selecting'); }",
//            "select2:select" => "function() { log('select'); }",
//            "select2:unselecting" => "function() { log('unselecting'); }",
//            "select2:unselect" => "function() { log('unselect'); }"
//        ],
    ])->label(false); ?>
    <?php ActiveForm::end(); ?>
</div>

views/records/_cdr_tree_view.php
<?php

use yii\widgets\Pjax;
use yii\web\JsExpression;
use execut\widget\TreeView;
use app\models\treeview\TreeViewGenerator;

$onSelect = new JsExpression(<<<JS
    function (undefined, item) {
        if (item.href !== location.pathname) {
            $.pjax({
                container: '#pjax-container',
                url: item.href,
                timeout: null
            });
        }

            var otherTreeWidgetEl = $('.treeview.small').not($(this)),
            otherTreeWidget = otherTreeWidgetEl.data('treeview'),
            selectedEl = otherTreeWidgetEl.find('.node-selected');
            if (selectedEl.length) {
                otherTreeWidget.unselectNode(Number(selectedEl.attr('data-nodeid')));
            }
    }
JS
);

$treeView = new TreeViewGenerator();
foreach ($datesModel as $model) {
    $treeView->addItem($model, $currentUrl);
}
$items = $treeView->getItems();

echo TreeView::widget([
'data' => $items,
'size' => TreeView::SIZE_MIDDLE,
'template' => TreeView::TEMPLATE_SIMPLE,
'clientOptions' => [
        'onNodeSelected' => $onSelect,
        'showTags' => true,
        'showBorder' => false,
    ],
]);

views/records/_menu.php
<?php
/* @var $navbar array menu items */

use yii\bootstrap\Nav;

?>

<?= Nav::widget([
    'options' => [
        'class' => 'nav-tabs',
        'style' => 'margin-bottom: 15px',
    ],
    'items' => $navbar,
]) ?>

views/records/_search.php
<?php

/* @var $model app\models\records\CdrOperatorSearch */
/* @var $channel array available channels for current user */

use app\assets\searchAsset;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\jui\DatePicker;
use yii\jui\AutoComplete;
use kartik\select2\Select2;
use yii\web\JsExpression;

searchAsset::register($this);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <?php
        $form = ActiveForm::begin([
            'method' => 'get',
            'action' => Url::toRoute(['', 'id' => Yii::$app->request->get('id')]),
            'fieldConfig' => [
                'options' => [
                    'class' => 'form-group form-group-sm',
                ],
            ],
        ]); ?>

        <?= $form->field($model, 'calldate')->widget(DatePicker::className(), [
            'dateFormat' => 'php:Y-m-d',
            'language' => 'ru',
            'clientOptions' => [
                'maxDate' => '+0D',
            ],
            'options' => [
                'class' => 'form-control',
                'placeholder' => 'Pick a preferred date',
            ],
        ]) ?>

        <?php if (Yii::$app->controller->route === 'records/group') : ?>
            <?= $form->field($model, 'channel')->widget(Select2::className(), [
                'data' => $channel,
                'theme' => 'bootstrap',
                'attribute' => 'channel',
                'maintainOrder' => true,
                'size' => 'sm',
                'options' => [
                    'placeholder' => 'Select operator ...',
                    'multiple' => false,
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                    'data' => true,
                ],
            ]) ?>
        <?php else: ?>
            <?= $form->field($model, 'channel')->hiddenInput()->label(false) ?>
        <?php endif; ?>

        <?= $form->field($model, 'phone')->widget(AutoComplete::className(), [
            'clientOptions' =>[
                'source' => New JsExpression("
                    function(request, response) {
                            var channel = $('#search-channel').val();
                            $.getJSON('".Url::toRoute(['/records/client-search'])."?channel=' + channel, {
                                phone: request.term
                            }, response);
                        }"
                ),
                'minLength' => '5',
            ],
            'options' => ['placeholder' => 'Enter client phone number', 'class' => 'form-control'],
        ]) ?>

        <?= \yii\helpers\Html::submitButton('Search', ['class' => 'btn btn-primary btn-sm btn-block']) ?>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/records/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>


    <?= \yii\grid\GridView::widget([
        'dataProvider' => $model->getCallDetailRecordsForUser(),
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'], //отображает номера строк
            'acctid',
            'src',
            'dst',
//            [
//                'class' => 'yii\grid\ActionColumn',
//                'template' => '{accept}',
//                'buttons' => [
//                    'accept' => function($url, $model) {
//                        $url = \yii\helpers\Url::toRoute(['/komplat/print', 'acctid' => $model->id]);
//                        return \yii\helpers\Html::a('<span class="glyphicon glyphicon-print"></span>', $url, [
//                            'title' => 'Распечатать договор',
//                            'data-pjax' => '0', // нужно для отключения для данной ссылки стандартного обработчика pjax. Поверьте, он все портит
//                        ]);
//                    }
//                ],
//            ],
        ],
    ]) ?>

</div>

views/records/cdr-worked.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = 'Call Detail Records';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="call-detail-record">
    <h1><?= Html::encode($this->title) ?></h1>


    <?= \yii\grid\GridView::widget([
        'dataProvider' => $model,
        'tableOptions' => [
            'class' => 'table table-bordered table-hover'
        ],
        //http://stackoverflow.com/questions/28381221/gridview-row-as-link-except-action-column-items-in-yii2
        'rowOptions' => function ($model, $key, $index, $grid) {
            return ['data-id' => $model->acctid];
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'], //отображает номера строк
            'acctid',
            'src',
            'dst',
            'recordfile',
//            [
//                'class' => 'yii\grid\ActionColumn',
//                'template' => '{accept}',
//                'buttons' => [
//                    'accept' => function($url, $model) {
//                        $url = \yii\helpers\Url::toRoute(['/komplat/print', 'acctid' => $model->id]);
//                        return \yii\helpers\Html::a('<span class="glyphicon glyphicon-print"></span>', $url, [
//                            'title' => 'Распечатать договор',
//                            'data-pjax' => '0', // нужно для отключения для данной ссылки стандартного обработчика pjax. Поверьте, он все портит
//                        ]);
//                    }
//                ],
//            ],
        ],
    ]) ?>

    <?php
    $this->registerJs("

    $('td').click(function (e) {
        var id = $(this).closest('tr').data('id');
        if(e.target == this)
            location.href = '" . Yii::$app->urlManager->createUrl('accountinfo/update') . "?id=' + id;
    });

");?>

<!--    --><?//= DetailView::widget([
//        'model' => $model,
//        'attributes' => [
//            'title',               // title свойство (обычный текст)
//            'description:html',    // description свойство, как HTML
//            [                      // name свойство зависимой модели owner
//               'label' => 'Cdr',
//                'value' => '123',
//            ],
//            'created_at:datetime', // дата создания в формате datetime
//        ],
//    ]);
//    ?>

</div>

views/records/cdr.php
<?php

/* @var $this yii\web\View */
/* @var $datesModel app\models\Cdr */
/* @var $searchModel app\models\CdrSearch */
/* @var $currentUrl bool */

use yii\helpers\Html;
use app\assets\jexpandAsset;
use app\models\CdrProfile;
use yii\helpers\ArrayHelper;
use app\assets\searchAsset;
use kartik\select2\Select2;

jexpandAsset::register($this);
searchAsset::register($this);
$this->title = 'Call Detail Records';
$this->params['breadcrumbs'][] = $this->title;
//var_dump(\yii\helpers\ArrayHelper::map(\app\models\CdrProfile::find()->asArray()->all(), 'inner_phone', 'sip_account')); exit;
?>
<div class="selectize-search">
<!--    <label class="control-label">Provinces</label>-->
    <?= Select2::widget([
        'name' => 'state_2',
        'value' => '',
        'data' => ['1', '2'],
        'options' => ['multiple' => true, 'placeholder' => 'Select states ...']
    ]);
    ?>
</div>

<div class="row">
<!--<div class="call-detail-record">-->
    <?php \yii\widgets\Pjax::begin(['id' => 'pjax-container',]); ?>

    <div class="call-detail-record-search col-md-2">
        <?//= $this->render('_cdr_tree_view', [
//            'datesModel' => $datesModel,
//            'currentUrl' => $currentUrl,
//            ]) ?>


    </div>

    <div class="col-md-10">

        <?= \yii\grid\GridView::widget([
        'dataProvider' => $model,
//        'filterModel' => $searchModel,
        'tableOptions' => [
            'class' => 'table table-bordered table-hover table-condensed',
            'id' => 'cdr',
        ],
        'rowOptions' => function ($model, $key, $index, $grid) {
            return ['data-id' => $model->acctid, 'class' => 'odd'];
        },
        'afterRow' => function($model, $key, $index) {
            return
                Html::tag('tr',
                    Html::tag('td',
                        Html::tag('span',''),
                    ['colspan'=>'5']),
                ['style' => 'display: none;']
            );
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'], //отображает номера строк
            'calldate',
            [
                'class' => \yii\grid\DataColumn::className(), // Не обязательно
                'attribute' => function($model) {
                    Yii::$app->formatter->timeZone = 'UTC';
                    return Yii::$app->formatter->asTime($model->billsec, 'php:H:i:s');
                },
                'label' => Yii::t('app', 'Duration'),
            ],
            [
                'class' => \yii\grid\DataColumn::className(), // Не обязательно
                'attribute' => function($model) {
                    $in = (Html::tag('div',Html::tag('i', '', ['class' => 'fa fa-sign-in fa-2x']),['class' => 'icons']));
                    $out = (Html::tag('div',Html::tag('i', '', ['class' => 'fa fa-sign-out fa-2x']),['class' => 'icons']));
                    return (strlen($model->src) > 4) ? $in : $out;
                },
                'format' => 'html',
                'label' => 'Type',
            ],
            [
                'class' => \yii\grid\DataColumn::className(), // Не обязательно
                'attribute' => function($model) {
                    //https://github.com/giggsey/libphonenumber-for-php
                    $phoneNumber = strlen($model->src) > 4 ? $model->src : $model->dst;
                    $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
                    try {
                        $phoneNumberObject = $phoneUtil->parse($phoneNumber, "BY");
                        return $phoneUtil->format($phoneNumberObject, \libphonenumber\PhoneNumberFormat::NATIONAL);
                    } catch (\libphonenumber\NumberParseException $e) {
                        return $phoneNumber;
                    }
                },
                'format' => 'html',
                'label' => 'Number',
            ],
            [
//                'class' => \yii\grid\DataColumn::className(), // Не обязательно
                'attribute' => function($model) {
                    //TODO это же ведь костыль, поэтому надо подумать как выбирать лучше, например по dstchannel делать кросс запрос в базу, и от туда доставать полное имя специалиста.
                    $operator = strlen($model->src) > 4 ? substr($model->dstchannel, 4, 3) : $model->src;
                    $operator = (Html::tag('a',$operator,['href'=> \yii\helpers\Url::to(['records/operator', 'number' => $operator, 'date' => Yii::$app->request->get('date')]), 'data-pjax' => 0, 'target' => '_blank']));
                    return $operator;
                },
                'format' => 'html',
                'label' => 'Operator',
//                'filter' => Html::activeListBox($searchModel, 'channel', ArrayHelper::map(CdrProfile::find()->asArray()->all(), 'sip_account', 'inner_phone')),
            ],
        ],
    ]) ?>
    <?php \yii\widgets\Pjax::end(); ?>
    </div>
</div>

views/records/cdr_test.php
<?php

/* @var $this yii\web\View */
/* @var $dataProvider app\models\records\Cdr */
/* @var $searchModel app\models\records\CdrOperatorSearch */
/* @var $navBar array menu items */
/* @var $channel array available channels for current user */
/* @var $currentUrl bool */

use yii\helpers\Html;
use app\assets\jexpandAsset;
use app\assets\spectrumPickerAsset;
spectrumPickerAsset::register($this);

jexpandAsset::register($this);
//if (!is_null($searchModel)) {
//    echo $this->render('_cdr_search_operator', ['model' => $searchModel]);
//}
//var_dump($cdrProfile->groups); exit;

?>
<?= $this->render('_menu', ['navbar' => $navBar]) ?>

<div class="row">
    <div class="col-lg-8 col-sm-2">
        <?php
        echo \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
            'summary' => false,
            'tableOptions' => [
                'class' => 'table table-bordered table-hover table-condensed',
                'id' => 'cdr',
            ],
            'rowOptions' => function ($model) {
                return ['data-id' => $model->acctid, 'class' => 'odd', 'style'=> 'background-color:'. $model->recordInfo['color'] .';'];
            },
            'afterRow' => function() {
                return
                    Html::tag('tr',
                        Html::tag('td',
                            Html::tag('span',Html::tag('td','',['colspan'=>'6'])),
                            ['colspan'=>'6']),
                        ['style' => 'display: none;']
                    );
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'], //отображает номера строк
                [
                    'attribute' => 'calldate',
                    'value' => 'calldate',
//                    'filter' => \yii\jui\DatePicker::widget([
//                        'model' => $searchModel,
//                        'attribute' => 'calldate',
//                        'dateFormat' => 'php:Y-m-d',
//                        'language' => 'ru',
//                        'clientOptions' => [
//                            'maxDate' => '+0D'
//                        ],
//                        'options' => [
//                            'class' => 'form-control',
//                        ],
//                    ]),
                    'format' => 'html',
                ],
                'call_duration', // вычисляемое в mysql запросе поле, фактически в таблице его нет.
                [
                    'attribute' => function($model) {
                        $in = (Html::tag('div',Html::tag('i', '', ['class' => 'fa fa-sign-in fa-2x']),['class' => 'icons']));
                        $out = (Html::tag('div',Html::tag('i', '', ['class' => 'fa fa-sign-out fa-2x']),['class' => 'icons']));
                        return $model->direction === 'in' ? $in : $out; // вычисляемое в mysql запросе поле, фактически в таблице его нет.
                    },
                    'format' => 'html',
                    'label' => 'Type',
                    'enableSorting' => false,

                ],
                'clientPhone',
                [
                    'attribute' => function($model) {
                        //TODO это же ведь костыль, поэтому надо подумать как выбирать лучше, например по dstchannel делать кросс запрос в базу, и от туда доставать полное имя специалиста.
                        $operator = strlen($model->src) > 4 ? substr($model->dstchannel, 4, 3) : $model->src;
        //                $operator = (Html::tag('a',$operator,['href'=> \yii\helpers\Url::to(['records/operator', 'number' => $operator, 'date' => Yii::$app->request->get('date')]), 'data-pjax' => 0, 'target' => '_blank']));
                        return $operator;
                    },
                    'format' => 'html',
                    'label' => 'Operator',
                    'enableSorting' => false,
                    'visible' => Yii::$app->controller->route === 'records/group',
//                    'filter' => \kartik\select2\Select2::widget([
//                        'data' => $channel,
//                        'theme' => 'bootstrap',
//                        'attribute' => 'channel',
//                        'model' => $searchModel,
//                        'maintainOrder' => true,
//                        'size' => 'sm',
//                        'options' => [
//                            'placeholder' => 'Select operator ...',
//                            'multiple' => false,
//                        ],
//                        'pluginOptions' => [
//                            'allowClear' => true,
//                            'data' => true,
//                        ],
//                    ]),
                ],
            ],
        ]);
        ?>
    </div>
    <div class="col-lg-4 col-sm-2">
        <?= $this->render('_search', ['model' => $searchModel, 'channel' => $channel]) ?>
    </div>
</div>